
theme: minima
skin: auto
header_pages:
  - about.md
  - rules.md
# minima:
#  date_format: "%b %-d, %Y"
#  date_format: "%b %-d, %Y"


lsi: false
safe: true
source: /web/
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
